name: job1
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hey there!This is job 1"
  
  my-job2:
    runs-on: ubuntu-latest
    needs : my-job
    steps:
      - name: job2
        run: pip install -r requirements.txt
